name: sissyphus
description: A Flutter app showcasing interactive trading view and order books interface powered by Binance's WebSockets API.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  gap: ^3.0.0
  candlesticks: ^2.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  
flutter:
  uses-material-design: true

  assets:
    - assets/icons/

  fonts:
    - family: Satoshi
      fonts:
        - asset: assets/fonts/Satoshi-Black.otf
          weight: 900
        - asset: assets/fonts/Satoshi-Bold.otf
          weight: 800
        - asset: assets/fonts/Satoshi-Medium.otf
          weight: 700
        - asset: assets/fonts/Satoshi-Regular.otf
          weight: 600
        - asset: assets/fonts/Satoshi-Regular.otf
          weight: 500
        - asset: assets/fonts/Satoshi-Light.otf
          weight: 400
        - asset: assets/fonts/Satoshi-Light.otf
          weight: 300
  
